CREATE DATABASE v;

CREATE ROLE v CREATEROLE LOGIN PASSWORD '12345';
GRANT ALL ON DATABASE v TO v WITH GRANT OPTION;
ALTER DATABASE v OWNER TO v;

CREATE EXTENSION IF NOT EXISTS "pgcrypto" SCHEMA public;