BEGIN;

CREATE ROLE didenko CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE karamanutsa CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE lyisenko CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE mangir CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE radilov CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE rusnak CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE shleht CREATEROLE LOGIN PASSWORD '12345';
CREATE ROLE shtyirba CREATEROLE LOGIN PASSWORD '12345';

GRANT ALL ON DATABASE didenko TO didenko WITH GRANT OPTION;
GRANT ALL ON DATABASE karamanutsa TO karamanutsa WITH GRANT OPTION;
GRANT ALL ON DATABASE lyisenko TO lyisenko WITH GRANT OPTION;
GRANT ALL ON DATABASE mangir TO mangir WITH GRANT OPTION;
GRANT ALL ON DATABASE radilov TO radilov WITH GRANT OPTION;
GRANT ALL ON DATABASE rusnak TO rusnak WITH GRANT OPTION;
GRANT ALL ON DATABASE shleht TO shleht WITH GRANT OPTION;
GRANT ALL ON DATABASE shtyirba TO shtyirba WITH GRANT OPTION;

COMMIT;